kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: jp.icr.io/cti-roks-training/cicd-app2:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
      imagePullSecrets:
        - name: all-icr-io
---
kind: Service
apiVersion: v1
metadata:
  name: app2
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: app2
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app2
spec:
  to:
    kind: Service
    name: app2
  tls:
    termination: edge
  port:
    targetPort: http-8081
